# VNC Client addon image for containers that have a VNC Server 

FROM nginx

COPY index.html /usr/share/nginx/html/
COPY core/ /usr/share/nginx/html/core/
COPY vendor/ /usr/share/nginx/html/vendor/
COPY app/ /usr/share/nginx/html/app/






