apiVersion: v1
kind: Service
metadata:
  name: kali-service
  labels:
    lab: example
    system: attacker
spec:
  selector:
    lab: example
    system: attacker
  ports:
    - port: 80
      targetPort: 80
    - port: 8080
      targetPort: 8080
    - port: 5900
      targetPort: 5900
