# This cluster role allows the Athena application to create, read update and delete the following resource types in all namespaces:
# - Deployments
# - Services
# - NetworkPolicies
# - Ingresses

# It also allow the application to read information about the following:
# - Pods
# - Namespaces
# In addition to the read access given to Namespaces, the Athena application can create new namespaces.



apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: athena-app-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch", "create"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["networkpolicies"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies", "ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
