kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: athena-app-database
  namespace: athena-app
  labels:
    app: athena
    role: database
spec:
  podSelector:
    matchLabels:
      app: athena
      role: database
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: athena
            role: frontend
      ports:
      - port: 1433
    - from:
      - namespaceSelector:
          matchLabels:
            name: kube-system
        podSelector:
          matchLabels: 
            k8s-app: kube-dns
  egress:
    - to:
      - podSelector:
          matchLabels:
            app: athena
            role: frontend
    - to:
      - namespaceSelector:
          matchLabels:
            name: kube-system
        podSelector:
          matchLabels: 
            k8s-app: kube-dns
          

