apiVersion: v1
kind: PersistentVolume
metadata:
  name: athena-templates
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs: # 
    path: # Your share path  
    server: # Your NFS server