apiVersion: v1
kind: PersistentVolume
metadata:
  name: athena-db-store
spec:
  capacity:
    storage: 200Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs: # 
    path: # Your share path  
    server: # Your NFS server