# This Secret object stores the credentials needed to sign in to the SQL Server database

apiVersion: v1
kind: Secret
metadata:
  name: athena-db-pw
  namespace: athena-app
type: Opaque

stringData: # Replace <password> in connection_str with your chosen password for the database.
  connection_str: "Data Source=athena-db.athena-app,1433;Database=ApplicationDB;User ID=SA;Password=<YourStrong@Passw0rd>;"
  sa_password: "<YourStrong@Passw0rd>"

	    