apiVersion: apps/v1
kind: Deployment
metadata:
  name: athena-app
  labels:
    app: athena
    role: frontend
spec:
  selector:
    matchLabels:
      app: athena
      role: frontend
  template:
    metadata:
      labels:
        app: athena
        role: frontend
    spec:
      serviceAccountName: athena-service-account
      containers:
        - name: athena-app
          image: #APP IMAGE HERE
          ports:
            - containerPort: 80
          env:
            - name:
              value: