apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: templates-claim
  namespace: athena-app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 100Mi