apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    lab: example
    system: web-app
    net: dmz
spec:
  selector:
    matchLabels:
      lab: example
      system: web-app
      net: dmz
  template:
    metadata:
      labels:
        lab: example
        system: web-app
        net: dmz        
    spec:
      containers:
        - name: web-app
          image: appsecco/dsvw
          ports:
            - containerPort: 8000

            

