apiVersion: v1
kind: Service
metadata:
  name: server-web-terminal
  labels:
    lab: initial
spec:
  type: NodePort
  selector:
    app: ssh-server
    lab: initial
  ports:
    - port: 80
      targetPort: 80