apiVersion: v1
kind: Service
metadata:
  name: kali-tty
  labels:
    lab: example
    system: attacker
    net: external
spec:
  selector:
    lab: example
    system: attacker
    net: external
  ports:
    - name: tty
      port: 8080
      targetPort: 8080
