apiVersion: v1
kind: Service
metadata:
  name: ubuntu-no-publish
  labels:
    lab: example
    system: client
    net: internal
spec:
  selector:
    lab: example
    system: client
    net: internal
  ports:
    - name: vnc
      port: 5900
      targetPort: 5900
