apiVersion: apps/v1
kind: Deployment
metadata:
  name: initial-client
  labels:
    app: test
spec:
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: ssh-client
          image: kali-ssh-client
          imagePullPolicy: Never
