apiVersion: v1
kind: Service
metadata:
  name: client-web-terminal
  labels:
    lab: initial
spec:
  type: NodePort
  selector:
    lab: initial
    app: ssh-client
  ports:
    - port: 80
      targetPort: 80
