apiVersion: v1
kind: Service
metadata:
  labels:
    app: webgoat
  name: webgoat
spec:
  type: NodePort
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  - name: "9001"
    port: 9001
    targetPort: 9001
  selector:
    app: webgoat

