apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-client
  labels:
    lab: example
    system: client
    net: internal
spec:
  selector:
    matchLabels:
      lab: example
      system: client
      net: internal    
  template:
    metadata:
      labels:
        lab: example
        system: client
        net: internal
    spec:
      containers:
        - name: ubuntu-client
          image: xyrvyre/athena:ubuntu-gui-base
          ports:
            - containerPort: 8080
            - containerPort: 5900
        - name: ubuntu-vnc
          image: xyrvyre/athena:vnc-client
          ports:
            - containerPort: 80
            

