apiVersion: apps/v1
kind: Deployment
metadata:
  name: webgoat
  labels:
    app: webgoat

spec:
  selector:
    matchLabels:
      app: webgoat
  template:
    metadata:
      labels:
        app: webgoat
    spec:
      containers:
        - name: webgoat
          image: webgoat/webgoat-8.0
          env:
          - name: TZ
            value: Pacific/Auckland
          - name: WEBWOLF_HOST
            value: webwolf
          - name: WEBWOLF_PORT
            value: "9090"
          
          ports:
          - containerPort: 8080
          - containerPort: 9001
          workingDir: /home/webgoat