apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webwolf
  name: webwolf
spec:
  selector:
    matchLabels:
      app: webwolf
  template:
    metadata:
      labels:
        app: webwolf
    spec:
      containers:
      - args:
        - "--spring.datasource.url=jdbc:hsqldb:hsql://webgoat:9001/webgoat"
        - "--server.address=0.0.0.0"
        image: webgoat/webwolf
        name: webwolf
        ports:
        - containerPort: 9090