apiVersion: v1
kind: Service
metadata:
  name: ubuntu-tty
  labels:
    lab: example
    system: client
    net: internal
spec:
  selector:
    lab: example
    system: client
    net: internal
  ports:
    - name: tty
      port: 8080
      targetPort: 8080

