apiVersion: v1
kind: Service
metadata:
  name: kali-vnc
  labels:
    lab: example
    system: attacker
    net: external
spec:
  selector:
    lab: example
    system: attacker
    net: external
  ports:
    - name: http
      port: 80
      targetPort: 80
